Do not hard-fail if formatting failed #23
wravery/webview2-rs pull request #24
Opened 2023-09-28 19:29 UTC by muja

Closes #23

2023-09-29 19:26 UTC, wravery requested changes

2023-09-29 19:26 UTC, wravery commented on crates/bindings/build.rs
> -        format_bindings(&source_path)?;
In other words, skip updating the bindings entirely if they cannot be formatted.

2023-09-29 19:38 UTC, wravery commented on crates/bindings/build.rs
> -        format_bindings(&source_path)?;
For example, in `main()`:
```rust
    if let Err(err) = webview2_bindgen::update_bindings() {
        eprintln!("Error updating bindings, using previous version: {err}");
    }
```

2023-10-15 23:43 UTC, muja commented on crates/bindings/build.rs
> -        format_bindings(&source_path)?;
I don't see the problem. Why would I (as a user) care about formatting in some build directory?
That is strictly a contributor's problem, they should be instructed to not create unformatted PRs

2023-10-16 01:38 UTC, wravery commented
Thank you for the PR! I decided to go with a different approach, though, removing all of the build-time code gen and making that a separate, explicit `update-bindings` tool to run when updating the `winmd` file.

2023-10-16 01:38 UTC, closed without merging

2023-10-16 15:12 UTC, muja commented
Good job. I wasn't thinking you'd be so fast, of course that's more sensible. Thank you very much!